
package app;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;

import javax.swing.JOptionPane;


/**
 *
 * @author fedec
 */
public class Clientes extends javax.swing.JFrame {

    /** Creates new form Cliente */
    public Clientes() {
        initComponents();
        LlenarCombo.conectar();
        jComboBox1.removeAllItems();
        ArrayList<String> traercategoria = new ArrayList<String>();
        traercategoria = LlenarCombo.llenar_combo1();
        for(int i = 0; i<traercategoria.size();i++){
        jComboBox1.addItem(traercategoria.get(i));
        }
        jComboBox2.removeAllItems();
        ArrayList<String> traervendedor = new ArrayList<String>();
        traervendedor = LlenarCombo.llenar_combo2();
        for(int i = 0; i<traervendedor.size();i++){
        jComboBox2.addItem(traervendedor.get(i));
        }
        jComboBox3.removeAllItems();
        ArrayList<String> traerzona = new ArrayList<String>();
        traerzona = LlenarCombo.llenar_combo3();
        for(int i = 0; i<traerzona.size();i++){
        jComboBox3.addItem(traerzona.get(i));
        }
        jComboBox4.removeAllItems();
        ArrayList<String> traerpais = new ArrayList<String>();
        traerpais = LlenarCombo.llenar_combo4();
        for(int i = 0; i<traerpais.size();i++){
        jComboBox4.addItem(traerpais.get(i));
        }
        jComboBox5.removeAllItems();
        ArrayList<String> traerprovincia = new ArrayList<String>();
        traerprovincia = LlenarCombo.llenar_combo5();
        for(int i = 0; i<traerprovincia.size();i++){
        jComboBox5.addItem(traerprovincia.get(i));
        }
        jComboBox6.removeAllItems();
        ArrayList<String> traerlocalidad = new ArrayList<String>();
        traerlocalidad = LlenarCombo.llenar_combo6();
        for(int i = 0; i<traerlocalidad.size();i++){
        jComboBox6.addItem(traerlocalidad.get(i));
        }
        jComboBox7.removeAllItems();
        ArrayList<String> traerestado = new ArrayList<String>();
        traerestado = LlenarCombo.llenar_combo7();
        for(int i = 0; i<traerestado.size();i++){
        jComboBox7.addItem(traerestado.get(i));
        }
        jTextField1.requestFocus();
    }
    public static boolean validarDNI(String numdni){
        return numdni.matches("[0-9]{1-8}");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 51));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 88, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN DE CLIENTES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel2.setText("N° de cliente:");

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(174, 88, 185));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel3.setText("DNI:");

        jTextField2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setText("CUIL/CUIT:");

        jTextField3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel5.setText("Nombre:");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setFocusable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel6.setText("Apellido:");

        jTextField5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel8.setText("-");

        jTextField6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel9.setText("Alias:");

        jTextField8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel10.setText("Correo electrónico:");

        jTextField9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel11.setText("Teléfono:");

        jTextField10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel12.setText("Dirección:");

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 205, 106));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setText("Agregar nuevo");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 222));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton3.setText("Buscar por N°");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 222));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton4.setText("Buscar por DNI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 128, 10));
        jButton5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton5.setText("Modificar por N°");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(174, 88, 185));
        jButton6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton6.setText("Mostrar todos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton7.setText("Limpiar campos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel13.setText("Categoría:");

        jTextField11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel14.setText("Vendedor:");

        jComboBox2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel15.setText("Zona:");

        jComboBox3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel16.setText("País:");

        jComboBox4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel17.setText("Provincia:");

        jComboBox5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel18.setText("Localidad:");

        jComboBox6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("Observaciones:");

        jTextField12.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextField12.setForeground(java.awt.Color.red);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel20.setText("Descuento fijo:");

        jTextField13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("-10");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel21.setText("Estado:");

        jComboBox7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jMenu1.setText("Vendedores");

        jMenuItem1.setText("Gestionar vendedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Zonas");

        jMenuItem2.setText("Gestionar zonas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ubicaciones");

        jMenuItem3.setText("Gestionar localidades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Gestionar provincias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Gestionar paises");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addGap(13, 13, 13)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel8)
                                .addGap(13, 13, 13)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20)
                                .addGap(13, 13, 13)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addGap(11, 11, 11)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addGap(13, 13, 13)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21)
                                .addGap(12, 12, 12)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)
                                .addGap(7, 7, 7)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addGap(14, 14, 14)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15)
                                .addGap(9, 9, 9)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel16)
                                .addGap(8, 8, 8)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel17)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addGap(8, 8, 8)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton7)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal inicio = new VentanaPrincipal();
        //inicio.setDefaultCloseOperation(inicio.HIDE_ON_CLOSE);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField2.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("-10");
        jTextField14.setText("");
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        String traer = jTextField2.getText();
        jTextField4.setText(traer);
    }//GEN-LAST:event_jTextField2FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //jTextField1.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
            String traer = jTextField2.getText();
            jTextField4.setText(traer);
            jTextField3.requestFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        jTextField5.requestFocus();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        jTextField6.requestFocus();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        jTextField7.requestFocus();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        jTextField8.requestFocus();
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
        jTextField9.requestFocus();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
        jTextField10.requestFocus();
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        jTextField11.requestFocus();
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        jTextField12.requestFocus();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
        jTextField13.requestFocus();
    }//GEN-LAST:event_jTextField12ActionPerformed
    public class AltaClienteC {
        public AltaClienteC(){
        }
        private String ultimoMensajeMySQL="";
        public String altaCliente(String dni, String precuil, String cuil, String sucuil, String desc1, String desc2, String nombre, String apellido, String alias, String email, String telefono, String direccion, int estado, int categoria, int vendedor, int zona, int pais, int provincia, int localidad, String observaciones) {
        String sql = "INSERT INTO picar_db.clientes (dni, cuil, nombre, apellido, alias, email, telefono, direccion, categoria_id, vendedor_id, zona_id, estado_id, pais_id, provincia_id, localidad_id, observaciones, descuentofijo1, descuentofijo2, fechaingreso) VALUES ("+dni+",'"+precuil+"-"+cuil+"-"+sucuil+"','"+nombre+"','"+apellido+"','"+alias+"','"+email+"',"+telefono+",'"+direccion+"',"+categoria+","+vendedor+","+zona+","+estado+","+pais+","+provincia+","+localidad+",'"+observaciones+"',"+desc1+","+desc2+",current_date());";
        try {
        Statement st = LlenarCombo.conexion.createStatement();
        st.executeUpdate(sql);
        ResultSet idcliente = st.executeQuery("select picar_db.clientes.idcliente from picar_db.clientes order by picar_db.clientes.idcliente desc limit 1;");
        if(idcliente.next()){
        String registroid = idcliente.getString("idcliente");
        st.executeUpdate("INSERT INTO picar_db.pagosclientes VALUES (0,"+registroid+",'',0,0,0,current_date());");
        ultimoMensajeMySQL="El cliente "+apellido+", "+nombre+" fue agregado con éxito al sistema.\nSu ID es: "+registroid+".";
        JOptionPane.showMessageDialog(null, ultimoMensajeMySQL, "INFORMACIÓN DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
        jTextField1.setText(registroid);
            }
        } catch (SQLException e) {
        System.out.println(e);
        JOptionPane.showMessageDialog(null, "ERROR: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return ultimoMensajeMySQL;
        }
    }
    private transient AltaClienteC acliente = new AltaClienteC();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String dni = this.jTextField2.getText();
        String precuil = this.jTextField3.getText();
        String cuil = this.jTextField4.getText();
        String sucuil = this.jTextField5.getText();
        String nombre = this.jTextField6.getText();
        String apellido = this.jTextField7.getText();
        String alias = this.jTextField8.getText();
        String email = this.jTextField9.getText();
        String telefono = this.jTextField10.getText();
        String direccion = this.jTextField11.getText();
        String observaciones = this.jTextField12.getText();
        String desc1 = this.jTextField13.getText();
        String desc2 = this.jTextField14.getText();
        int categoria = this.jComboBox1.getSelectedIndex()+1;
        int estado = this.jComboBox7.getSelectedIndex()+1;
        int vendedor = this.jComboBox2.getSelectedIndex()+1;
        int zona = this.jComboBox3.getSelectedIndex()+1;
        int pais = this.jComboBox4.getSelectedIndex()+1;
        int provincia = this.jComboBox5.getSelectedIndex()+1;
        int localidad = this.jComboBox6.getSelectedIndex()+1;
        acliente.altaCliente(dni.replace(" ", "").trim(),precuil.replace(" ", "").trim(),cuil.replace(" ", "").trim(),sucuil.replace(" ", "").trim(),desc1.replace(" ","").trim(),desc2.replace(" ","").trim(),nombre.toUpperCase().trim(),apellido.toUpperCase().trim(),alias.toUpperCase().trim(),email.toUpperCase().trim().replace(" ", ""),telefono.replace(" ","").trim(),direccion.toUpperCase().trim(),estado,categoria,vendedor,zona,pais,provincia,localidad,observaciones.toUpperCase().trim());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusLost

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AltaVendedor nuevovendedor = new AltaVendedor(this,true);
        this.dispose();
        nuevovendedor.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        nuevovendedor.setLocationRelativeTo(null);
        nuevovendedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AltaZona nuevazona = new AltaZona(this,true);
        this.dispose();
        nuevazona.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        nuevazona.setLocationRelativeTo(null);
        nuevazona.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
        jTextField14.requestFocus();
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
        jButton2.requestFocus();
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AltaLocalidad nuevalocalidad = new AltaLocalidad(this,true);
        this.dispose();
        nuevalocalidad.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        nuevalocalidad.setLocationRelativeTo(null);
        nuevalocalidad.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        AltaProvincia nuevaprovincia = new AltaProvincia(this,true);
        this.dispose();
        nuevaprovincia.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        nuevaprovincia.setLocationRelativeTo(null);
        nuevaprovincia.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AltaPais nuevaprovincia = new AltaPais(this,true);
        this.dispose();
        nuevaprovincia.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        nuevaprovincia.setLocationRelativeTo(null);
        nuevaprovincia.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MostrarTodosClientes mostrarclientes = new MostrarTodosClientes();
        this.dispose();
        mostrarclientes.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        mostrarclientes.setLocationRelativeTo(null);
        mostrarclientes.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed
    public class BuscarClienteC{
        public BuscarClienteC(){
        }
        public String buscarCliente(String idcliente){
            try{
                Statement st = LlenarCombo.conexion.createStatement();
                ResultSet registrocliente = st.executeQuery("SELECT * FROM picar_db.clientes WHERE clientes.idcliente="+idcliente+";");
                if(registrocliente.next()){
                String traerdni = registrocliente.getString("dni");
                String traerdescuento1 = registrocliente.getString("descuentofijo1");
                String traerdescuento2 = registrocliente.getString("descuentofijo2");
                String traernombre = registrocliente.getString("nombre");
                String traerapellido = registrocliente.getString("apellido");
                String traeralias = registrocliente.getString("alias");
                String traercorreo = registrocliente.getString("email");
                String traertelefono = registrocliente.getString("telefono");
                String traerdireccion = registrocliente.getString("direccion");
                String traerobservacion = registrocliente.getString("observaciones");
                String traercuil = registrocliente.getString("cuil");
                String precuil = traercuil.substring(0,2);
                String sucuil = traercuil.substring(12);
                int traerestado = registrocliente.getInt("estado_id");
                int traercategoria = registrocliente.getInt("categoria_id");
                int traervendedor = registrocliente.getInt("vendedor_id");
                int traerzona = registrocliente.getInt("zona_id");
                int traerpais = registrocliente.getInt("pais_id");
                int traerprovincia = registrocliente.getInt("provincia_id");
                int traerlocalidad = registrocliente.getInt("localidad_id");
                jTextField2.setText(traerdni);
                jTextField3.setText(precuil);
                jTextField4.setText(traerdni);
                jTextField5.setText(sucuil);
                jTextField6.setText(traernombre);
                jTextField7.setText(traerapellido);
                jTextField8.setText(traeralias);
                jTextField9.setText(traercorreo);
                jTextField10.setText(traertelefono);
                jTextField11.setText(traerdireccion);
                jTextField12.setText(traerobservacion);
                jTextField13.setText(traerdescuento1);
                jTextField14.setText(traerdescuento2);
                jComboBox7.setSelectedIndex(traerestado-1);
                jComboBox1.setSelectedIndex(traercategoria-1);
                jComboBox2.setSelectedIndex(traervendedor-1);
                jComboBox3.setSelectedIndex(traerzona-1);
                jComboBox4.setSelectedIndex(traerpais-1);
                jComboBox5.setSelectedIndex(traerprovincia-1);
                jComboBox6.setSelectedIndex(traerlocalidad-1);
                }else{
                    JOptionPane.showMessageDialog(null, "El cliente N°"+idcliente+" ingresado no se encuentra en el sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                }
            } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "ERROR: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            return idcliente;
        }
    }
    private transient BuscarClienteC bcliente = new BuscarClienteC();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idcliente = this.jTextField1.getText();
        bcliente.buscarCliente(idcliente.replace(" ", "").trim());
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed
    public class BuscarClienteCDNI{
        public BuscarClienteCDNI(){
        }
        public String buscarClienteDNI(String dnicliente){
            try{
                Statement st = LlenarCombo.conexion.createStatement();
                ResultSet registrocliente = st.executeQuery("SELECT * FROM picar_db.clientes WHERE clientes.dni="+dnicliente+";");
                if(registrocliente.next()){
                String traerid = registrocliente.getString("idcliente");
                String traerdescuento1 = registrocliente.getString("descuentofijo1");
                String traerdescuento2 = registrocliente.getString("descuentofijo2");
                String traernombre = registrocliente.getString("nombre");
                String traerapellido = registrocliente.getString("apellido");
                String traeralias = registrocliente.getString("alias");
                String traercorreo = registrocliente.getString("email");
                String traertelefono = registrocliente.getString("telefono");
                String traerdireccion = registrocliente.getString("direccion");
                String traerobservacion = registrocliente.getString("observaciones");
                String traercuil = registrocliente.getString("cuil");
                String precuil = traercuil.substring(0,2);
                String sucuil = traercuil.substring(12);
                int traerestado = registrocliente.getInt("estado_id");
                int traercategoria = registrocliente.getInt("categoria_id");
                int traervendedor = registrocliente.getInt("vendedor_id");
                int traerzona = registrocliente.getInt("zona_id");
                int traerpais = registrocliente.getInt("pais_id");
                int traerprovincia = registrocliente.getInt("provincia_id");
                int traerlocalidad = registrocliente.getInt("localidad_id");
                jTextField1.setText(traerid);
                jTextField3.setText(precuil);
                jTextField5.setText(sucuil);
                jTextField6.setText(traernombre);
                jTextField7.setText(traerapellido);
                jTextField8.setText(traeralias);
                jTextField9.setText(traercorreo);
                jTextField10.setText(traertelefono);
                jTextField11.setText(traerdireccion);
                jTextField12.setText(traerobservacion);
                jTextField13.setText(traerdescuento1);
                jTextField14.setText(traerdescuento2);
                jComboBox7.setSelectedIndex(traerestado-1);
                jComboBox1.setSelectedIndex(traercategoria-1);
                jComboBox2.setSelectedIndex(traervendedor-1);
                jComboBox3.setSelectedIndex(traerzona-1);
                jComboBox4.setSelectedIndex(traerpais-1);
                jComboBox5.setSelectedIndex(traerprovincia-1);
                jComboBox6.setSelectedIndex(traerlocalidad-1);
                jTextField2.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "El cliente con DNI "+dnicliente+" ingresado no se encuentra en el sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField2.requestFocus();
                }
            } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "ERROR: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            return dnicliente;
        }
    }
    private transient BuscarClienteCDNI bclientedni = new BuscarClienteCDNI();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dnicliente = this.jTextField2.getText();
        bclientedni.buscarClienteDNI(dnicliente.replace(" ", "").trim());
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed
    public class ModificarClienteC{
        public ModificarClienteC(){
        }
        private String ultimoMensajeMySQL="";
        public String modificarCliente (String idcliente, String dni, String precuil, String cuil, String sucuil, String desc1, String desc2, String nombre, String apellido, String alias, String email, String telefono, String direccion, int estado, int categoria, int vendedor, int zona, int pais, int provincia, int localidad, String observaciones){
        String sql = "UPDATE picar_db.clientes SET dni='"+dni+"', cuil='"+precuil+"-"+cuil+"-"+sucuil+"', nombre='"+nombre+"', apellido='"+apellido+"', alias='"+alias+"', email='"+email+"', telefono="+telefono+", direccion='"+direccion+"', categoria_id="+categoria+", vendedor_id="+vendedor+", zona_id="+zona+", estado_id="+estado+", pais_id="+pais+", provincia_id="+provincia+", localidad_id="+localidad+", observaciones='"+observaciones+"', descuentofijo1="+desc1+", descuentofijo2="+desc2+" WHERE idcliente="+idcliente+";";
            try{
                Statement st = LlenarCombo.conexion.createStatement();
                st.executeUpdate(sql);
                ultimoMensajeMySQL="El cliente N°"+idcliente+" fue actualizado con los datos ingresados.";
                ResultSet registrocliente = st.executeQuery("SELECT * FROM picar_db.clientes WHERE idcliente="+idcliente+";");
                if(registrocliente.next()){
                    JOptionPane.showMessageDialog(null, ultimoMensajeMySQL, "INFORMACIÓN DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                    String traerdni = registrocliente.getString("dni");
                    String traerdescuento1 = registrocliente.getString("descuentofijo1");
                    String traerdescuento2 = registrocliente.getString("descuentofijo2");
                    String traernombre = registrocliente.getString("nombre");
                    String traerapellido = registrocliente.getString("apellido");
                    String traeralias = registrocliente.getString("alias");
                    String traercorreo = registrocliente.getString("email");
                    String traertelefono = registrocliente.getString("telefono");
                    String traerdireccion = registrocliente.getString("direccion");
                    String traerobservacion = registrocliente.getString("observaciones");
                    String traercuil = registrocliente.getString("cuil");
                    String precuil2 = traercuil.substring(0,2);
                    String sucuil2 = traercuil.substring(12);
                    int traerestado = registrocliente.getInt("estado_id");
                    int traercategoria = registrocliente.getInt("categoria_id");
                    int traervendedor = registrocliente.getInt("vendedor_id");
                    int traerzona = registrocliente.getInt("zona_id");
                    int traerpais = registrocliente.getInt("pais_id");
                    int traerprovincia = registrocliente.getInt("provincia_id");
                    int traerlocalidad = registrocliente.getInt("localidad_id");
                    jTextField2.setText(traerdni);
                    jTextField3.setText(precuil2);
                    jTextField4.setText(traerdni);
                    jTextField5.setText(sucuil2);
                    jTextField6.setText(traernombre);
                    jTextField7.setText(traerapellido);
                    jTextField8.setText(traeralias);
                    jTextField9.setText(traercorreo);
                    jTextField10.setText(traertelefono);
                    jTextField11.setText(traerdireccion);
                    jTextField12.setText(traerobservacion);
                    jTextField13.setText(traerdescuento1);
                    jTextField14.setText(traerdescuento2);
                    jComboBox7.setSelectedIndex(traerestado-1);
                    jComboBox1.setSelectedIndex(traercategoria-1);
                    jComboBox2.setSelectedIndex(traervendedor-1);
                    jComboBox3.setSelectedIndex(traerzona-1);
                    jComboBox4.setSelectedIndex(traerpais-1);
                    jComboBox5.setSelectedIndex(traerprovincia-1);
                    jComboBox6.setSelectedIndex(traerlocalidad-1);
                    jTextField1.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "El cliente N°"+idcliente+" ingresado no se encuentra en el sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    LlenarCombo.conectar();
                    jComboBox1.removeAllItems();
                    ArrayList<String> traercategoria = new ArrayList<String>();
                    traercategoria = LlenarCombo.llenar_combo1();
                    for(int i = 0; i<traercategoria.size();i++){
                    jComboBox1.addItem(traercategoria.get(i));
                    }
                    jComboBox2.removeAllItems();
                    ArrayList<String> traervendedor = new ArrayList<String>();
                    traervendedor = LlenarCombo.llenar_combo2();
                    for(int i = 0; i<traervendedor.size();i++){
                    jComboBox2.addItem(traervendedor.get(i));
                    }
                    jComboBox3.removeAllItems();
                    ArrayList<String> traerzona = new ArrayList<String>();
                    traerzona = LlenarCombo.llenar_combo3();
                    for(int i = 0; i<traerzona.size();i++){
                    jComboBox3.addItem(traerzona.get(i));
                    }
                    jComboBox4.removeAllItems();
                    ArrayList<String> traerpais = new ArrayList<String>();
                    traerpais = LlenarCombo.llenar_combo4();
                    for(int i = 0; i<traerpais.size();i++){
                    jComboBox4.addItem(traerpais.get(i));
                    }
                    jComboBox5.removeAllItems();
                    ArrayList<String> traerprovincia = new ArrayList<String>();
                    traerprovincia = LlenarCombo.llenar_combo5();
                    for(int i = 0; i<traerprovincia.size();i++){
                    jComboBox5.addItem(traerprovincia.get(i));
                    }
                    jComboBox6.removeAllItems();
                    ArrayList<String> traerlocalidad = new ArrayList<String>();
                    traerlocalidad = LlenarCombo.llenar_combo6();
                    for(int i = 0; i<traerlocalidad.size();i++){
                    jComboBox6.addItem(traerlocalidad.get(i));
                    }
                    jComboBox7.removeAllItems();
                    ArrayList<String> traerestado = new ArrayList<String>();
                    traerestado = LlenarCombo.llenar_combo7();
                    for(int i = 0; i<traerestado.size();i++){
                    jComboBox7.addItem(traerestado.get(i));
                    }
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");
                    jTextField13.setText("-10");
                    jTextField14.setText("");
                    jTextField1.requestFocus();
                }
            } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "ERROR: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
            return ultimoMensajeMySQL;
    }
    }
    private transient ModificarClienteC mcliente = new ModificarClienteC();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String idcliente = this.jTextField1.getText();
        String dni = this.jTextField2.getText();
        String precuil = this.jTextField3.getText();
        String cuil = this.jTextField4.getText();
        String sucuil = this.jTextField5.getText();
        String nombre = this.jTextField6.getText();
        String apellido = this.jTextField7.getText();
        String alias = this.jTextField8.getText();
        String email = this.jTextField9.getText();
        String telefono = this.jTextField10.getText();
        String direccion = this.jTextField11.getText();
        String observaciones = this.jTextField12.getText();
        String desc1 = this.jTextField13.getText();
        String desc2 = this.jTextField14.getText();
        int categoria = this.jComboBox1.getSelectedIndex()+1;
        int estado = this.jComboBox7.getSelectedIndex()+1;
        int vendedor = this.jComboBox2.getSelectedIndex()+1;
        int zona = this.jComboBox3.getSelectedIndex()+1;
        int pais = this.jComboBox4.getSelectedIndex()+1;
        int provincia = this.jComboBox5.getSelectedIndex()+1;
        int localidad = this.jComboBox6.getSelectedIndex()+1;
        mcliente.modificarCliente(idcliente.replace(" ", "").trim(),dni.replace(" ", "").trim(),precuil.replace(" ", "").trim(),cuil.replace(" ", "").trim(),sucuil.replace(" ", "").trim(),desc1.replace(" ","").trim(),desc2.replace(" ","").trim(),nombre.toUpperCase().trim(),apellido.toUpperCase().trim(),alias.toUpperCase().trim(),email.toUpperCase().trim().replace(" ", ""),telefono.replace(" ","").trim(),direccion.toUpperCase().trim(),estado,categoria,vendedor,zona,pais,provincia,localidad,observaciones.toUpperCase().trim());

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Clientes.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Clientes.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Clientes.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Clientes.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Clientes().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
